### ISSUE TITLE
devloper mode not working

### ISSUE THREAD

**Issue by NOTBOOSTER** [BlueprintFramework/framework#49]
### Current Behavior

![Screenshot 2024-07-05 111916](https://github.com/BlueprintFramework/framework/assets/169513679/99ab615f-ab42-4553-a2d3-822f1b4df12f)
![Screenshot 2024-07-05 111924](https://github.com/BlueprintFramework/framework/assets/169513679/986be7be-8611-4c4d-9dab-fc56f983a9ca)

idk why i am getting this while enabling devloper mode

### Expected Behavior

i have followed docs and tried to enable developer mode 

### Steps to Reproduce

i have followed docs and tried to enable developer mode 

### Blueprint Version

beta-F248

### Panel Version

1.11.7

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details and tested my reproduction steps.
- [X] I have checked to my best capabilities and believe this is a bug with the software, and not a configuration issue with my specific system.
- [X] I have made sure to check that this bug is the fault of Blueprint and is not caused by stock Pterodactyl.

**Comment by MrAstro18** [comment]
Run this command on your terminal
blueprint -upgrade remote blueprintframework/framework

**Comment by NOTBOOSTER** [comment]
oh thanks fixed

**Comment by MrAstro18** [comment]
Have a nice day :)

**Comment by prplwtf** [comment]
Just a quick thank you for taking the time to report any bugs you encountered. We've been receiving multiple reports about this one and it'll definitely be fixed in the next release.
