### ISSUE TITLE
Database Migrations broken

### ISSUE THREAD

**Issue by 0x7d8** [BlueprintFramework/framework#52]
### Current Behavior

when installing extension, the migration files get copied but `php artisan migrate --force` never gets ran

### Expected Behavior

`php artisan migrate --force` gets ran after finishing all extensions

### Steps to Reproduce

Install any extension with migrations defined

### Blueprint Version

beta-2024-07

### Panel Version

1.11.7

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details and tested my reproduction steps.
- [X] I have checked to my best capabilities and believe this is a bug with the software, and not a configuration issue with my specific system.
- [X] I have made sure to check that this bug is the fault of Blueprint and is not caused by stock Pterodactyl.

**Comment by prplwtf** [comment]
The following `if` statement checks for database migrations from a `local` variable, of which it does not have access to. This small oversight results in database migrations never being ran.

https://github.com/BlueprintFramework/framework/blob/0bab40b248e871132e357927ac04db8272b5b362/scripts/commands/extensions/install.sh#L1301-L1309

**Comment by prplwtf** [comment]
Fixed in https://github.com/BlueprintFramework/framework/commit/644ab3e424bcae7ea48b61fa2dbe80a80ed0e137.
