### ISSUE TITLE
Extension update scripts

### ISSUE THREAD

**Issue by prplwtf** [BlueprintFramework/framework#56]
### Scope

CLI

### Explanation

(https://discord.com/channels/1063548024825057451/1094955970100203581/1300527539390910514)

..add upgrade scripts**, etc.\
[..]\
\*\* Updating extensions on Blueprint **should not** be the same behavior as removing an extension, then installing it again. To solve this, we could implement upgrade scripts which would be ran when updating an extension.
- To make updating from each extension version possible, update scripts would be ran differently compared to install/remove scripts. When updating an extension, Blueprint should run the upgrade script of the __currently installed__ extension as early as possible in an extension transaction.
- Install scripts will still be ran at the end of an extension transaction even when updating.
- Update scripts are meant to remove all the out-of-scope modifications before new ones are added by the install script.

### Is there an existing issue for this?

- [x] I have searched the existing issues before opening this issue.

**Comment by 0x7d8** [comment]
close @prplwtf
