### ISSUE TITLE
/app doesnt exist and it still trys to install there and reports it as a successful install when its not a successful install and blue print just fails to work afterwads

### ISSUE THREAD

**Issue by katy-the-kat** [BlueprintFramework/framework#70]
### Current Behavior

blueprint doesnt work (it thinks it installed in /apps and it doesnt work)

![image](https://github.com/user-attachments/assets/cad7e067-caa5-4e69-860a-d5e4aa2b22ce)
![image](https://github.com/user-attachments/assets/c08df0bd-796b-4103-a506-224b2b5ce45c)
![image](https://github.com/user-attachments/assets/480eb7be-20c1-4e67-be83-b60e3c939b58)

### Expected Behavior

Should work and mkdir /app and mkdir .blueprint

### Steps to Reproduce

idk

### Blueprint Version

2024-08 (i dont know, blueprint -version doesnt work)

### Panel Version

1.11.10

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details and tested my reproduction steps.
- [X] I have checked to my best capabilities and believe this is a bug with the software, and not a configuration issue with my specific system.
- [X] I have made sure to check that this bug is the fault of Blueprint and is not caused by stock Pterodactyl.

**Comment by prplwtf** [comment]
Bug reports require reproduction steps. Please create a discussion post instead seeking for community support.

**Comment by katy-the-kat** [comment]
Are you stupid ahh
